import { User } from '@/types/user';
import { Trainer } from '@/types/trainer';
import { MembershipPlan, UserMembership } from '@/types/membership';
import { Program, Exercise, WorkoutProgress } from '@/types/workout';
import { Booking } from '@/types/booking';
import { AttendanceRecord, AttendanceMonthlySummary } from '@/types/attendance';
import { PaymentTransaction } from '@/types/payment';
import { Notification } from '@/types/notification';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Alex Johnson',
    email: 'alex@example.com',
    phone: '+91 98765 11111',
    role: 'member',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    isActive: true,
    profile: {
      id: 'prof-1',
      userId: 'usr-1',
      age: 26,
      gender: 'male',
      height: 178,
      weight: 76.5,
      targetWeight: 80,
      fitnessGoal: 'muscle_gain',
      activityLevel: 'very_active',
      bmi: 24.1,
      bodyFatPercentage: 14.5,
      assignedTrainerId: 'trn-1',
      assignedTrainerName: 'Marcus Vance',
      emergencyContactName: 'Sarah Johnson',
      emergencyContactPhone: '+91 98765 22222',
      medicalConditions: 'None',
    },
  },
  {
    id: 'usr-2',
    name: 'Marcus Vance',
    email: 'marcus@ironforge.com',
    phone: '+91 98765 33333',
    role: 'trainer',
    avatarUrl: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=300&auto=format&fit=crop&q=80',
    createdAt: '2023-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
    isActive: true,
  },
  {
    id: 'usr-3',
    name: 'Admin Boss',
    email: 'admin@ironforge.com',
    phone: '+91 98765 00000',
    role: 'admin',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    createdAt: '2022-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
    isActive: true,
  },
  {
    id: 'usr-4',
    name: 'Priya Patel',
    email: 'priya@example.com',
    phone: '+91 98765 44444',
    role: 'member',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-05-15T10:00:00Z',
    isActive: true,
    profile: {
      id: 'prof-4',
      userId: 'usr-4',
      age: 29,
      gender: 'female',
      height: 165,
      weight: 58.0,
      targetWeight: 55,
      fitnessGoal: 'weight_loss',
      activityLevel: 'moderate',
      bmi: 21.3,
      bodyFatPercentage: 21.0,
      assignedTrainerId: 'trn-2',
      assignedTrainerName: 'Elena Rostova',
    },
  },
  {
    id: 'usr-5',
    name: 'David Miller',
    email: 'david@example.com',
    phone: '+91 98765 55555',
    role: 'member',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-04-10T10:00:00Z',
    isActive: false,
  },
];

export const INITIAL_TRAINERS: Trainer[] = [
  {
    id: 'trn-1',
    userId: 'usr-2',
    name: 'Marcus Vance',
    title: 'Head Strength & Conditioning Coach',
    email: 'marcus@ironforge.com',
    phone: '+91 98765 33333',
    avatarUrl: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=500&auto=format&fit=crop&q=80',
    specialization: 'Strength Coach',
    secondarySpecializations: ['Bodybuilding Pro', 'Powerlifting'],
    experienceYears: 11,
    rating: 4.9,
    reviewCount: 142,
    bio: 'Former national powerlifting champion with over a decade of coaching elite athletes and beginners to break personal strength records and build explosive power.',
    certifications: ['CSCS Certified Strength Specialist', 'ISSA Master Trainer', 'USAW Level 2 Coach'],
    socialLinks: {
      instagram: 'https://instagram.com',
      twitter: 'https://twitter.com',
      youtube: 'https://youtube.com',
    },
    achievements: ['Coached 40+ state medalists', 'National Squat Record Holder 2018'],
    hourlyRate: 1500,
    activeClientsCount: 18,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    availableTimeSlots: ['06:00 AM - 07:00 AM', '07:30 AM - 08:30 AM', '05:00 PM - 06:00 PM', '06:30 PM - 07:30 PM'],
    isFeatured: true,
  },
  {
    id: 'trn-2',
    name: 'Elena Rostova',
    title: 'CrossFit & Metabolic Conditioning Lead',
    email: 'elena@ironforge.com',
    phone: '+91 98765 33334',
    avatarUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
    specialization: 'CrossFit Coach',
    secondarySpecializations: ['HIIT Specialist', 'Weight Loss Coach'],
    experienceYears: 8,
    rating: 4.95,
    reviewCount: 118,
    bio: 'Specializes in high-intensity functional training, Olympic gymnastics, and cardiovascular endurance programming designed to melt fat and enhance athletic work capacity.',
    certifications: ['CrossFit Level 3 Trainer (CF-L3)', 'ACE Certified Personal Trainer', 'Precision Nutrition Level 1'],
    socialLinks: {
      instagram: 'https://instagram.com',
      linkedin: 'https://linkedin.com',
    },
    achievements: ['CrossFit Regional Qualifier 2021', 'Ironman 70.3 Finisher'],
    hourlyRate: 1400,
    activeClientsCount: 22,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableTimeSlots: ['07:00 AM - 08:00 AM', '08:30 AM - 09:30 AM', '06:00 PM - 07:00 PM', '07:30 PM - 08:30 PM'],
    isFeatured: true,
  },
  {
    id: 'trn-3',
    name: 'Karan Mehra',
    title: 'Clinical Nutrition & Body Recomposition Coach',
    email: 'karan@ironforge.com',
    phone: '+91 98765 33335',
    avatarUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500&auto=format&fit=crop&q=80',
    specialization: 'Nutrition Coach',
    secondarySpecializations: ['Weight Loss Coach', 'Bodybuilding Pro'],
    experienceYears: 9,
    rating: 4.88,
    reviewCount: 95,
    bio: 'Combines clinical nutritional biochemistry with periodized hypertrophy training to deliver sustainable body transformations without restrictive fads.',
    certifications: ['Precision Nutrition Master Coach (Pn2)', 'ISSN Sports Nutritionist', 'NASM-CPT'],
    socialLinks: {
      instagram: 'https://instagram.com',
      youtube: 'https://youtube.com',
    },
    achievements: ['Published Author on Metabolic Flexibility', 'Transformed 500+ corporate clients'],
    hourlyRate: 1600,
    activeClientsCount: 15,
    availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    availableTimeSlots: ['08:00 AM - 09:00 AM', '10:00 AM - 11:00 AM', '04:00 PM - 05:00 PM', '07:00 PM - 08:00 PM'],
    isFeatured: true,
  },
  {
    id: 'trn-4',
    name: 'Aria Chen',
    title: 'Holistic Yoga & Mobility Master',
    email: 'aria@ironforge.com',
    phone: '+91 98765 33336',
    avatarUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=500&auto=format&fit=crop&q=80',
    specialization: 'Yoga Instructor',
    secondarySpecializations: ['Functional Training', 'Mobility Specialist'],
    experienceYears: 7,
    rating: 4.92,
    reviewCount: 88,
    bio: 'Dedicated to injury prevention, joint longevity, fascial release, and breath-synchronized flow to balance heavy lifting with supreme flexibility and core stability.',
    certifications: ['ERYT-500 Yoga Alliance', 'FRC Mobility Specialist', 'TRX Suspension Master'],
    socialLinks: {
      instagram: 'https://instagram.com',
      youtube: 'https://youtube.com',
    },
    achievements: ['Trained Olympic gymnasts', 'Keynote speaker at Global Wellness Summit'],
    hourlyRate: 1300,
    activeClientsCount: 20,
    availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday', 'Sunday'],
    availableTimeSlots: ['06:30 AM - 07:30 AM', '08:00 AM - 09:00 AM', '05:30 PM - 06:30 PM', '07:00 PM - 08:00 PM'],
    isFeatured: true,
  },
  {
    id: 'trn-5',
    name: 'Devon Reed',
    title: 'Metabolic Fat Loss & Transformation Specialist',
    email: 'devon@ironforge.com',
    phone: '+91 98765 33337',
    avatarUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
    specialization: 'Weight Loss Coach',
    secondarySpecializations: ['HIIT Specialist', 'Strength Coach'],
    experienceYears: 6,
    rating: 4.85,
    reviewCount: 76,
    bio: 'High-energy coach committed to fat loss acceleration, metabolic priming, and sustainable lifestyle habit formulation for long-term health.',
    certifications: ['ACE Certified Fitness Coach', 'Kettlebell Athletics Level 2'],
    socialLinks: {
      instagram: 'https://instagram.com',
      twitter: 'https://twitter.com',
    },
    achievements: ['Over 1,200kg of total client fat loss achieved'],
    hourlyRate: 1200,
    activeClientsCount: 14,
    availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday', 'Saturday'],
    availableTimeSlots: ['06:00 AM - 07:00 AM', '09:00 AM - 10:00 AM', '06:00 PM - 07:00 PM'],
    isFeatured: false,
  },
];

export const INITIAL_MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: 'plan-basic',
    name: 'Basic',
    tagline: 'Essential access for dedicated fitness enthusiasts',
    monthlyPrice: 999,
    yearlyPrice: 9590, // ~20% off
    isPopular: false,
    accessHours: 'Standard Hours (06:00 AM - 10:00 PM)',
    guestPassesPerMonth: 1,
    trainerSessionsPerMonth: 0,
    dietConsultationsPerQuarter: 0,
    saunaAccess: false,
    lockerAccess: true,
    features: [
      { title: 'Full Gym Floor & Free Weights Access', included: true },
      { title: 'Cardio & Strength Machine Zone', included: true },
      { title: 'Standard Locker & Shower Facilities', included: true },
      { title: 'Mobile App Workout Progress Tracker', included: true },
      { title: '1 Complimentary Guest Pass / Month', included: true },
      { title: 'Personal Trainer Sessions', included: false },
      { title: 'Customized Diet & Nutrition Plan', included: false },
      { title: 'Infrared Sauna & Recovery Lounge', included: false },
      { title: 'All Group Fitness & CrossFit Classes', included: false },
    ],
  },
  {
    id: 'plan-pro',
    name: 'Pro',
    tagline: 'The ultimate fitness package for accelerated transformations',
    monthlyPrice: 1999,
    yearlyPrice: 19190, // ~20% off
    isPopular: true,
    accessHours: 'All Hours (05:00 AM - 11:00 PM)',
    guestPassesPerMonth: 4,
    trainerSessionsPerMonth: 2,
    dietConsultationsPerQuarter: 1,
    saunaAccess: true,
    lockerAccess: true,
    features: [
      { title: 'All Basic Tier Inclusions', included: true },
      { title: 'Unlimited Group Classes (HIIT, CrossFit, Yoga)', included: true },
      { title: '2 Personal Training Sessions / Month', included: true },
      { title: 'Personalized Nutrition & Meal Guide', included: true },
      { title: 'Infrared Sauna & Steam Room Access', included: true },
      { title: 'Priority Equipment & Class Booking', included: true },
      { title: '4 Complimentary Guest Passes / Month', included: true },
      { title: 'InBody Body Composition Scans (Monthly)', included: true },
      { title: 'Dedicated Private VIP Locker', included: false },
    ],
  },
  {
    id: 'plan-elite',
    name: 'Elite',
    tagline: 'VIP concierge fitness experience with dedicated personal coaching',
    monthlyPrice: 3499,
    yearlyPrice: 33590, // ~20% off
    isPopular: false,
    accessHours: '24/7 Unlimited VIP Access',
    guestPassesPerMonth: 10,
    trainerSessionsPerMonth: 8,
    dietConsultationsPerQuarter: 3,
    saunaAccess: true,
    lockerAccess: true,
    features: [
      { title: 'All Pro Tier Inclusions', included: true },
      { title: '8 One-on-One Personal Training Sessions / Month', included: true },
      { title: 'Dedicated Master Coach & WhatsApp Support', included: true },
      { title: 'Bi-Weekly Nutrition & Macro Adjustments', included: true },
      { title: 'Permanent Private VIP Locker & Laundry Service', included: true },
      { title: 'Unlimited Sauna, Ice Bath & Hydrotherapy', included: true },
      { title: 'Complimentary Pre-Workout & Protein Shake Bar', included: true },
      { title: '10 Complimentary Guest Passes / Month', included: true },
      { title: 'Exclusive Access to Elite Masterclasses', included: true },
    ],
  },
];

export const INITIAL_USER_MEMBERSHIP: UserMembership = {
  id: 'mem-1',
  userId: 'usr-1',
  planId: 'plan-pro',
  plan: INITIAL_MEMBERSHIP_PLANS[1],
  status: 'active',
  billingInterval: 'monthly',
  amountPaid: 1999,
  startDate: '2024-07-01T00:00:00Z',
  endDate: '2024-08-31T23:59:59Z',
  daysRemaining: 21,
  autoRenew: true,
  paymentId: 'pay_ironforge_9921',
};

export const INITIAL_EXERCISES: Exercise[] = [
  {
    id: 'ex-1',
    name: 'Barbell Bench Press',
    targetMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Deltoids'],
    difficulty: 'Intermediate',
    sets: 4,
    reps: '8-10',
    restTimeSeconds: 90,
    caloriesBurnedEstimate: 120,
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Lie flat on bench with eyes aligned directly beneath the bar.',
      'Grip the bar slightly wider than shoulder width with thumbs wrapped around.',
      'Unrack, take a deep breath, retract your shoulder blades, and lower the bar smoothly to mid-chest.',
      'Press the bar explosively back to starting position while exhaling.',
    ],
    equipmentNeeded: 'Barbell, Olympic Flat Bench, Weight Plates',
    tips: ['Keep your feet flat on the floor', 'Do not bounce the bar off your sternum'],
  },
  {
    id: 'ex-2',
    name: 'Incline Dumbbell Press',
    targetMuscle: 'Chest',
    secondaryMuscles: ['Upper Chest', 'Anterior Deltoids'],
    difficulty: 'Intermediate',
    sets: 3,
    reps: '10-12',
    restTimeSeconds: 75,
    caloriesBurnedEstimate: 95,
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Set an adjustable bench to a 30 to 45 degree angle.',
      'Hold dumbbells on thighs and kick them up to shoulder level as you lie back.',
      'Press up in an arc until arms are extended, pausing briefly at the peak.',
      'Control the descent down until your upper chest feels a full stretch.',
    ],
    equipmentNeeded: 'Adjustable Bench, Dumbbells',
  },
  {
    id: 'ex-3',
    name: 'Deadlift (Conventional)',
    targetMuscle: 'Back',
    secondaryMuscles: ['Hamstrings', 'Glutes', 'Traps', 'Forearms'],
    difficulty: 'Advanced',
    sets: 5,
    reps: '5',
    restTimeSeconds: 150,
    caloriesBurnedEstimate: 180,
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Stand with feet hip-width apart, barbell over mid-foot.',
      'Hinge at hips to grip the bar just outside your shins.',
      'Engage lats, brace your core, flatten back, and drive through the floor to stand tall.',
      'Lock hips and knees simultaneously at the top, then lower with control.',
    ],
    equipmentNeeded: 'Olympic Barbell, Bumper Plates, Chalk',
  },
  {
    id: 'ex-4',
    name: 'Barbell Back Squat',
    targetMuscle: 'Legs',
    secondaryMuscles: ['Quadriceps', 'Glutes', 'Calves', 'Core'],
    difficulty: 'Advanced',
    sets: 4,
    reps: '6-8',
    restTimeSeconds: 120,
    caloriesBurnedEstimate: 160,
    imageUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Rest barbell securely across upper traps with hands gripping firm.',
      'Step back, set feet shoulder-width with toes slightly flared.',
      'Inhale deep into diaphragm, hinge hips back and bend knees until thighs are parallel to ground.',
      'Drive powerfully out of the hole through the mid-foot.',
    ],
    equipmentNeeded: 'Squat Rack, Barbell, Weight Plates',
  },
  {
    id: 'ex-5',
    name: 'Pull-Ups / Lat Pulldown',
    targetMuscle: 'Back',
    secondaryMuscles: ['Biceps', 'Rear Delts', 'Rhomboids'],
    difficulty: 'Intermediate',
    sets: 4,
    reps: '8-12',
    restTimeSeconds: 90,
    caloriesBurnedEstimate: 110,
    imageUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Grip the pull-up bar slightly wider than shoulder-width with overhand grip.',
      'Pull your chest up toward the bar by driving your elbows down and back.',
      'Squeeze lats at the top, hold for 1 second, then lower under control.',
    ],
    equipmentNeeded: 'Pull-up Bar or Lat Pulldown Machine',
  },
  {
    id: 'ex-6',
    name: 'Overhead Standing Military Press',
    targetMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Upper Traps', 'Core'],
    difficulty: 'Intermediate',
    sets: 4,
    reps: '8-10',
    restTimeSeconds: 90,
    caloriesBurnedEstimate: 105,
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Hold barbell across collarbone with elbows positioned directly under wrists.',
      'Brace glutes and abs to avoid lumbar hyperextension.',
      'Press barbell vertically overhead until arms lock out with head through the window.',
      'Slowly lower back down to collarbone.',
    ],
    equipmentNeeded: 'Barbell, Squat Stand',
  },
  {
    id: 'ex-7',
    name: 'Standing Barbell Bicep Curls',
    targetMuscle: 'Arms',
    secondaryMuscles: ['Brachialis', 'Forearms'],
    difficulty: 'Beginner',
    sets: 3,
    reps: '10-12',
    restTimeSeconds: 60,
    caloriesBurnedEstimate: 70,
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Stand upright holding EZ curl bar or straight bar with palms facing forward.',
      'Keep elbows pinned closely to your ribs.',
      'Curl weight up while contracting biceps, avoiding swinging the torso.',
      'Lower under 3-second negative eccentric tempo.',
    ],
    equipmentNeeded: 'EZ Curl Bar or Barbell',
  },
  {
    id: 'ex-8',
    name: 'Hanging Leg Raises',
    targetMuscle: 'Abs',
    secondaryMuscles: ['Hip Flexors', 'Obliques'],
    difficulty: 'Intermediate',
    sets: 3,
    reps: '12-15',
    restTimeSeconds: 60,
    caloriesBurnedEstimate: 60,
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Hang from pull-up bar with straight arms and legs together.',
      'Engage lower core and raise legs without swinging until they are parallel to floor or higher.',
      'Slowly lower back down to prevent pendulum momentum.',
    ],
    equipmentNeeded: 'Pull-up Bar',
  },
  {
    id: 'ex-9',
    name: 'High Intensity Assault Bike Sprint',
    targetMuscle: 'Cardio',
    secondaryMuscles: ['Full Body', 'Quads', 'Lungs'],
    difficulty: 'Advanced',
    sets: 6,
    reps: '30s sprint / 45s rest',
    restTimeSeconds: 45,
    caloriesBurnedEstimate: 200,
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Mount the air assault bike and adjust seat height.',
      'Pedal and push/pull handles with maximum all-out anaerobic power for 30 seconds.',
      'Pedal easy during the rest interval before next round.',
    ],
    equipmentNeeded: 'Air Assault Bike',
  },
  {
    id: 'ex-10',
    name: 'Barbell Clean and Press',
    targetMuscle: 'Full Body',
    secondaryMuscles: ['Shoulders', 'Legs', 'Traps', 'Core'],
    difficulty: 'Advanced',
    sets: 5,
    reps: '5',
    restTimeSeconds: 120,
    caloriesBurnedEstimate: 175,
    imageUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Clean barbell dynamically from floor to rack position across front shoulders.',
      'Dip slightly at the knees and drive through legs to push press the barbell overhead.',
      'Lower under control back to shoulders, then hips, then floor.',
    ],
    equipmentNeeded: 'Olympic Barbell & Bumper Plates',
  },
];

export const INITIAL_PROGRAMS: Program[] = [
  {
    id: 'prog-1',
    title: 'Weight Training',
    slug: 'weight-training',
    shortDescription: 'Master compound lifting mechanics, progressive overload, and foundational strength.',
    fullDescription: 'Our signature Weight Training program systematically builds real-world force production, posture alignment, and tendon resilience through structured barbell and dumbbell resistance cycles.',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    difficulty: 'Intermediate',
    durationWeeks: 12,
    sessionsPerWeek: 4,
    estimatedCaloriesPerSession: 450,
    trainerName: 'Marcus Vance',
    trainerAvatar: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=300&auto=format&fit=crop&q=80',
    trainerId: 'trn-1',
    enrolledCount: 142,
    rating: 4.9,
    equipment: ['Barbells', 'Squat Racks', 'Dumbbells', 'Cable Machines'],
    scheduleOverview: [
      { day: 'Day 1', focus: 'Upper Body Heavy Push (Bench & Overhead)', duration: '60 mins' },
      { day: 'Day 2', focus: 'Lower Body Quad Dominant (Squat & Accessories)', duration: '60 mins' },
      { day: 'Day 3', focus: 'Active Mobility & Core Recovery', duration: '45 mins' },
      { day: 'Day 4', focus: 'Upper Body Heavy Pull (Deadlift & Rows)', duration: '60 mins' },
      { day: 'Day 5', focus: 'Lower Body Posterior Chain & Calves', duration: '60 mins' },
    ],
    exercises: [INITIAL_EXERCISES[0], INITIAL_EXERCISES[2], INITIAL_EXERCISES[3], INITIAL_EXERCISES[4]],
  },
  {
    id: 'prog-2',
    title: 'Muscle Building',
    slug: 'muscle-building',
    shortDescription: 'Optimized hypertrophy volume protocols designed for maximal muscle fiber recruitment.',
    fullDescription: 'High-density hypertrophy regimen utilizing scientifically backed rest-pause sets, drop sets, and time-under-tension protocols to sculpt an imposing, symmetrical physique.',
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80',
    difficulty: 'Intermediate',
    durationWeeks: 10,
    sessionsPerWeek: 5,
    estimatedCaloriesPerSession: 500,
    trainerName: 'Karan Mehra',
    trainerAvatar: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=300&auto=format&fit=crop&q=80',
    trainerId: 'trn-3',
    enrolledCount: 210,
    rating: 4.95,
    equipment: ['Free Weights', 'Cable Pulleys', 'Incline Benches'],
    scheduleOverview: [
      { day: 'Day 1', focus: 'Chest & Triceps Hypertrophy', duration: '65 mins' },
      { day: 'Day 2', focus: 'Back & Biceps Width and Thickness', duration: '65 mins' },
      { day: 'Day 3', focus: 'Shoulders & Traps 3D Sculpt', duration: '60 mins' },
      { day: 'Day 4', focus: 'Legs & Calves Volume Matrix', duration: '70 mins' },
      { day: 'Day 5', focus: 'Arms & Core Isolation Overload', duration: '55 mins' },
    ],
    exercises: [INITIAL_EXERCISES[0], INITIAL_EXERCISES[1], INITIAL_EXERCISES[4], INITIAL_EXERCISES[6]],
  },
  {
    id: 'prog-3',
    title: 'Weight Loss',
    slug: 'weight-loss',
    shortDescription: 'High-caloric metabolic expenditure combining resistance with interval complexes.',
    fullDescription: 'Ignite stubborn fat stores through lactate-threshold conditioning, metabolic finishers, and nutrition synchronicity engineered to protect lean mass while shedding body fat.',
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop&q=80',
    difficulty: 'Beginner',
    durationWeeks: 8,
    sessionsPerWeek: 4,
    estimatedCaloriesPerSession: 600,
    trainerName: 'Devon Reed',
    trainerAvatar: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=300&auto=format&fit=crop&q=80',
    trainerId: 'trn-5',
    enrolledCount: 320,
    rating: 4.88,
    equipment: ['Kettlebells', 'Rowers', 'Dumbbells', 'Medicine Balls'],
    scheduleOverview: [
      { day: 'Day 1', focus: 'Total Body Metabolic Circuit', duration: '50 mins' },
      { day: 'Day 2', focus: 'HIIT Tabata Cardio & Core Shred', duration: '45 mins' },
      { day: 'Day 3', focus: 'Lower Body Fat Burn Complexes', duration: '50 mins' },
      { day: 'Day 4', focus: 'Upper Body Density Circuit', duration: '50 mins' },
    ],
    exercises: [INITIAL_EXERCISES[7], INITIAL_EXERCISES[8], INITIAL_EXERCISES[9]],
  },
  {
    id: 'prog-4',
    title: 'CrossFit',
    slug: 'crossfit',
    shortDescription: 'Constantly varied, functional movements performed at high intensity.',
    fullDescription: 'Push your mental and physical limits with Olympic weightlifting, gymnastics bar work, rope climbs, and heart-pounding WODs (Workouts of the Day) led by certified CrossFit coaches.',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    difficulty: 'Advanced',
    durationWeeks: 12,
    sessionsPerWeek: 5,
    estimatedCaloriesPerSession: 650,
    trainerName: 'Elena Rostova',
    trainerAvatar: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=300&auto=format&fit=crop&q=80',
    trainerId: 'trn-2',
    enrolledCount: 185,
    rating: 4.97,
    equipment: ['Gymnastic Rings', 'Bumper Plates', 'Air Bikes', 'Plyo Boxes'],
    scheduleOverview: [
      { day: 'Day 1', focus: 'Snatch Technique + 15 min AMRAP', duration: '60 mins' },
      { day: 'Day 2', focus: 'Gymnastic Ring Dips + Chipper WOD', duration: '60 mins' },
      { day: 'Day 3', focus: 'Clean & Jerk + EMOM Power Intervals', duration: '60 mins' },
      { day: 'Day 4', focus: 'Endurance Row/Bike Hero WOD', duration: '60 mins' },
      { day: 'Day 5', focus: 'Team Buddy Challenge & Mobility', duration: '60 mins' },
    ],
    exercises: [INITIAL_EXERCISES[2], INITIAL_EXERCISES[8], INITIAL_EXERCISES[9]],
  },
  {
    id: 'prog-5',
    title: 'HIIT',
    slug: 'hiit',
    shortDescription: 'Maximum calorie afterburn in short, intense bursts of anaerobic work.',
    fullDescription: 'Elevate your VO2 max and trigger the EPOC (afterburn) effect with heart-rate monitored sprint intervals, plyometrics, and athletic bodyweight agility drills.',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&auto=format&fit=crop&q=80',
    difficulty: 'Intermediate',
    durationWeeks: 6,
    sessionsPerWeek: 3,
    estimatedCaloriesPerSession: 550,
    trainerName: 'Elena Rostova',
    trainerAvatar: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=300&auto=format&fit=crop&q=80',
    trainerId: 'trn-2',
    enrolledCount: 260,
    rating: 4.89,
    equipment: ['Battle Ropes', 'Slam Balls', 'Treadmills', 'Agility Ladders'],
    scheduleOverview: [
      { day: 'Day 1', focus: 'Sprint Interval Ladder & Core', duration: '40 mins' },
      { day: 'Day 2', focus: 'Plyometric Athletic Power', duration: '40 mins' },
      { day: 'Day 3', focus: 'Battle Rope & Slam Matrix', duration: '40 mins' },
    ],
    exercises: [INITIAL_EXERCISES[7], INITIAL_EXERCISES[8]],
  },
  {
    id: 'prog-6',
    title: 'Yoga',
    slug: 'yoga',
    shortDescription: 'Asana flexibility, breathwork, joint decompression, and mental clarity.',
    fullDescription: 'Restore structural balance, open tight hip flexors and shoulders, enhance respiratory capacity, and cultivate bulletproof mindfulness with Vinyasa and Yin yoga disciplines.',
    imageUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&auto=format&fit=crop&q=80',
    difficulty: 'Beginner',
    durationWeeks: 8,
    sessionsPerWeek: 3,
    estimatedCaloriesPerSession: 250,
    trainerName: 'Aria Chen',
    trainerAvatar: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=300&auto=format&fit=crop&q=80',
    trainerId: 'trn-4',
    enrolledCount: 190,
    rating: 4.96,
    equipment: ['Yoga Mats', 'Cork Blocks', 'Strap Bands', 'Bolsters'],
    scheduleOverview: [
      { day: 'Day 1', focus: 'Vinyasa Dynamic Flow & Hip Openers', duration: '60 mins' },
      { day: 'Day 2', focus: 'Spine Decompression & Balance Holds', duration: '60 mins' },
      { day: 'Day 3', focus: 'Deep Yin Yoga & Pranayama Meditation', duration: '60 mins' },
    ],
    exercises: [],
  },
];

export const INITIAL_PROGRESS_LOGS: WorkoutProgress[] = [
  {
    id: 'log-1',
    userId: 'usr-1',
    date: '2024-07-01',
    weight: 81.2,
    bodyFatPercentage: 17.5,
    chest: 104,
    waist: 86,
    arms: 37,
    legs: 58,
    workoutDurationMinutes: 60,
    caloriesBurned: 480,
    notes: 'Started IRONFORGE Pro subscription. Initial testing day.',
  },
  {
    id: 'log-2',
    userId: 'usr-1',
    date: '2024-07-08',
    weight: 80.4,
    bodyFatPercentage: 16.9,
    chest: 104.5,
    waist: 85,
    arms: 37.5,
    legs: 58.5,
    workoutDurationMinutes: 65,
    caloriesBurned: 520,
    notes: 'Increased bench press by 5kg.',
  },
  {
    id: 'log-3',
    userId: 'usr-1',
    date: '2024-07-15',
    weight: 79.6,
    bodyFatPercentage: 16.2,
    chest: 105,
    waist: 84,
    arms: 38,
    legs: 59,
    workoutDurationMinutes: 60,
    caloriesBurned: 510,
    notes: 'Feeling lighter on runs and stronger on pull-ups.',
  },
  {
    id: 'log-4',
    userId: 'usr-1',
    date: '2024-07-22',
    weight: 78.5,
    bodyFatPercentage: 15.5,
    chest: 106,
    waist: 82.5,
    arms: 38.5,
    legs: 59.5,
    workoutDurationMinutes: 70,
    caloriesBurned: 580,
    notes: 'CrossFit WOD completed in under 18 minutes!',
  },
  {
    id: 'log-5',
    userId: 'usr-1',
    date: '2024-07-29',
    weight: 77.8,
    bodyFatPercentage: 15.0,
    chest: 106.5,
    waist: 81.5,
    arms: 39,
    legs: 60,
    workoutDurationMinutes: 65,
    caloriesBurned: 540,
    notes: 'Strict nutrition adherence. Energy levels through the roof.',
  },
  {
    id: 'log-6',
    userId: 'usr-1',
    date: '2024-08-05',
    weight: 76.5,
    bodyFatPercentage: 14.5,
    chest: 107,
    waist: 80,
    arms: 39.5,
    legs: 60.5,
    workoutDurationMinutes: 65,
    caloriesBurned: 560,
    notes: 'Hit personal record of 100kg bench press for 3 clean reps!',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-1',
    userId: 'usr-1',
    userName: 'Alex Johnson',
    userEmail: 'alex@example.com',
    userPhone: '+91 98765 11111',
    serviceType: 'Personal Trainer',
    trainerId: 'trn-1',
    trainerName: 'Marcus Vance',
    trainerAvatar: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=200&auto=format&fit=crop&q=80',
    date: '2026-08-22',
    timeSlot: '07:30 AM - 08:30 AM',
    status: 'confirmed',
    notes: 'Focus on heavy deadlift form and belt bracing technique.',
    createdAt: '2026-08-18T10:00:00Z',
    updatedAt: '2026-08-18T10:30:00Z',
  },
  {
    id: 'bk-2',
    userId: 'usr-1',
    userName: 'Alex Johnson',
    userEmail: 'alex@example.com',
    serviceType: 'CrossFit',
    trainerId: 'trn-2',
    trainerName: 'Elena Rostova',
    trainerAvatar: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=200&auto=format&fit=crop&q=80',
    date: '2026-08-24',
    timeSlot: '06:00 PM - 07:00 PM',
    status: 'confirmed',
    notes: 'Saturday squad conditioning workout.',
    createdAt: '2026-08-19T11:00:00Z',
    updatedAt: '2026-08-19T11:00:00Z',
  },
  {
    id: 'bk-3',
    userId: 'usr-4',
    userName: 'Priya Patel',
    userEmail: 'priya@example.com',
    serviceType: 'Yoga',
    trainerId: 'trn-4',
    trainerName: 'Aria Chen',
    trainerAvatar: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=200&auto=format&fit=crop&q=80',
    date: '2026-08-21',
    timeSlot: '08:00 AM - 09:00 AM',
    status: 'confirmed',
    notes: 'Spinal mobility and breathwork session.',
    createdAt: '2026-08-17T09:00:00Z',
    updatedAt: '2026-08-17T09:00:00Z',
  },
  {
    id: 'bk-4',
    userId: 'usr-1',
    userName: 'Alex Johnson',
    userEmail: 'alex@example.com',
    serviceType: 'Consultation',
    trainerId: 'trn-3',
    trainerName: 'Karan Mehra',
    trainerAvatar: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=200&auto=format&fit=crop&q=80',
    date: '2026-08-28',
    timeSlot: '10:00 AM - 11:00 AM',
    status: 'pending',
    notes: 'Monthly body composition review & macro adjustments.',
    createdAt: '2026-08-20T08:00:00Z',
    updatedAt: '2026-08-20T08:00:00Z',
  },
];

export const INITIAL_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  { id: 'att-1', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-01', status: 'present', checkInTime: '06:15 AM', checkOutTime: '07:45 AM', durationMinutes: 90, entryMethod: 'QR_CODE' },
  { id: 'att-2', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-02', status: 'present', checkInTime: '06:20 AM', checkOutTime: '07:35 AM', durationMinutes: 75, entryMethod: 'QR_CODE' },
  { id: 'att-3', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-03', status: 'absent' },
  { id: 'att-4', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-04', status: 'present', checkInTime: '06:30 AM', checkOutTime: '08:00 AM', durationMinutes: 90, entryMethod: 'CARD_TAP' },
  { id: 'att-5', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-05', status: 'present', checkInTime: '07:00 AM', checkOutTime: '08:15 AM', durationMinutes: 75, entryMethod: 'QR_CODE' },
  { id: 'att-6', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-06', status: 'present', checkInTime: '06:45 AM', checkOutTime: '08:10 AM', durationMinutes: 85, entryMethod: 'QR_CODE' },
  { id: 'att-7', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-07', status: 'absent' },
  { id: 'att-8', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-08', status: 'present', checkInTime: '06:10 AM', checkOutTime: '07:30 AM', durationMinutes: 80, entryMethod: 'QR_CODE' },
  { id: 'att-9', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-09', status: 'present', checkInTime: '06:25 AM', checkOutTime: '07:55 AM', durationMinutes: 90, entryMethod: 'QR_CODE' },
  { id: 'att-10', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-10', status: 'present', checkInTime: '06:40 AM', checkOutTime: '08:00 AM', durationMinutes: 80, entryMethod: 'QR_CODE' },
  { id: 'att-11', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-11', status: 'absent' },
  { id: 'att-12', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-12', status: 'present', checkInTime: '06:30 AM', checkOutTime: '07:50 AM', durationMinutes: 80, entryMethod: 'QR_CODE' },
  { id: 'att-13', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-13', status: 'present', checkInTime: '06:15 AM', checkOutTime: '07:40 AM', durationMinutes: 85, entryMethod: 'QR_CODE' },
  { id: 'att-14', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-14', status: 'present', checkInTime: '06:20 AM', checkOutTime: '07:45 AM', durationMinutes: 85, entryMethod: 'QR_CODE' },
  { id: 'att-15', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-15', status: 'holiday' }, // Independence Day
  { id: 'att-16', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-16', status: 'present', checkInTime: '06:35 AM', checkOutTime: '08:00 AM', durationMinutes: 85, entryMethod: 'QR_CODE' },
  { id: 'att-17', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-17', status: 'present', checkInTime: '06:10 AM', checkOutTime: '07:35 AM', durationMinutes: 85, entryMethod: 'QR_CODE' },
  { id: 'att-18', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-18', status: 'present', checkInTime: '06:15 AM', checkOutTime: '07:45 AM', durationMinutes: 90, entryMethod: 'QR_CODE' },
  { id: 'att-19', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-19', status: 'present', checkInTime: '06:20 AM', checkOutTime: '07:50 AM', durationMinutes: 90, entryMethod: 'QR_CODE' },
  { id: 'att-20', userId: 'usr-1', userName: 'Alex Johnson', date: '2026-08-20', status: 'present', checkInTime: '06:05 AM', checkOutTime: '07:30 AM', durationMinutes: 85, entryMethod: 'QR_CODE' },
];

export const INITIAL_PAYMENTS: PaymentTransaction[] = [
  {
    id: 'tx-1',
    userId: 'usr-1',
    userName: 'Alex Johnson',
    userEmail: 'alex@example.com',
    planId: 'plan-pro',
    planName: 'Pro Membership',
    amount: 1999,
    currency: 'INR',
    razorpayPaymentId: 'pay_ironforge_9921',
    razorpayOrderId: 'order_IF_00124',
    status: 'captured',
    paymentMethod: 'UPI',
    billingInterval: 'monthly',
    createdAt: '2026-08-01T10:15:00Z',
    invoiceNumber: 'INV-2026-0841',
  },
  {
    id: 'tx-2',
    userId: 'usr-4',
    userName: 'Priya Patel',
    userEmail: 'priya@example.com',
    planId: 'plan-elite',
    planName: 'Elite Membership',
    amount: 33590,
    currency: 'INR',
    razorpayPaymentId: 'pay_ironforge_8814',
    razorpayOrderId: 'order_IF_00125',
    status: 'captured',
    paymentMethod: 'Card',
    billingInterval: 'yearly',
    createdAt: '2026-08-05T14:30:00Z',
    invoiceNumber: 'INV-2026-0842',
  },
  {
    id: 'tx-3',
    userId: 'usr-5',
    userName: 'David Miller',
    userEmail: 'david@example.com',
    planId: 'plan-basic',
    planName: 'Basic Membership',
    amount: 999,
    currency: 'INR',
    razorpayPaymentId: 'pay_ironforge_7720',
    razorpayOrderId: 'order_IF_00126',
    status: 'failed',
    paymentMethod: 'NetBanking',
    billingInterval: 'monthly',
    createdAt: '2026-08-10T18:45:00Z',
    invoiceNumber: 'INV-2026-0843',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'usr-1',
    title: 'Personal Training Session Tomorrow',
    message: 'Your 1-on-1 session with Coach Marcus Vance is scheduled for tomorrow at 07:30 AM.',
    type: 'booking_confirmed',
    isRead: false,
    actionUrl: '/dashboard/bookings',
    createdAt: '2026-08-20T08:00:00Z',
  },
  {
    id: 'notif-2',
    userId: 'usr-1',
    title: 'Membership Renewal Reminder',
    message: 'Your Pro plan has 21 days remaining. Enable Auto-Renew to stay uninterrupted.',
    type: 'membership_expiry',
    isRead: false,
    actionUrl: '/membership',
    createdAt: '2026-08-19T09:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'usr-1',
    title: 'New PR Logged! 🎉',
    message: 'Congratulations! You logged a new bench press record of 100kg.',
    type: 'workout_reminder',
    isRead: true,
    actionUrl: '/dashboard/progress',
    createdAt: '2026-08-15T12:30:00Z',
  },
];
